"""init

Revision ID: 8d62c35aa959
Revises: dd33cb03d01f
Create Date: 2023-04-18 19:17:50.181995

"""

# revision identifiers, used by Alembic.
revision = '8d62c35aa959'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
